name: Default

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Clone

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Docker
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          image: danielyin/xxl-job-executor-sample-springboot
          addLatest: true
          directory: .
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
